version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: inventory_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #backend:
  #  build:
  #    context: ./backend
  # container_name: backend
  #  restart: always
  #  env_file:
  #    - ./backend/app/core/.env
  #  ports:
  #    - "8000:8000"
  #  depends_on:
  #    - db

  # frontend:
  #  build:
  #    context: ./frontend
  #  container_name: frontend
  #  restart: always
  #  env_file:
  #    - ./frontend/.env
  #  ports:
  #    - "3000:80"
  #  depends_on:
  #    - backend

volumes:
  postgres_data:
